markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: penger 
author: "be happy"
email: esc_penger#163.com
name: "博客"
url: http://penger.github.io
domain: penger.github.io
all_categories: [
["tags", "分类","/tags.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
